#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : smem
Version  : 1.4
Release  : 1
URL      : https://www.selenic.com/smem/download/smem-1.4.tar.gz
Source0  : https://www.selenic.com/smem/download/smem-1.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: smem-bin
Requires: smem-doc
Patch1: 0001-Add-Makefile.patch

%description
No detailed description available

%package bin
Summary: bin components for the smem package.
Group: Binaries

%description bin
bin components for the smem package.


%package doc
Summary: doc components for the smem package.
Group: Documentation

%description doc
doc components for the smem package.


%prep
%setup -q -n smem-1.4
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488830262
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1488830262
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smem

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
